### ISSUE TITLE
Tips: More data

### ISSUE THREAD

**Issue by psykzz** [Neamar/teamward-client#14]
Clicking the tip should allow you to see the data that informed the tip.
For example

Played more than 10 games in 24 hours

Clicking could show

12/03: Ryze (Win) - 20min
12/03: Ryze (Win) - 20min
12/03: Ryze (Win) - 20min
12/03: Ryze (Win) - 20min
12/03: Ryze (Win) - 20min
12/03: Ryze (Win) - 20min
12/03: Ryze (Win) - 20min
12/03: Ryze (Win) - 20min

**Comment by psykzz** [comment]
@Neamar POKE

**Comment by Neamar** [comment]
Might be possible to do once I've built a page to display more than one champion at a time. TBC.
