### ISSUE TITLE
Add keystone mastery.

### ISSUE THREAD

**Issue by psykzz** [Neamar/teamward-client#15]
Having the keystone mastery somewhere will really help determine the playstyle of the enemy team.

**Comment by psykzz** [comment]
@Neamar POKE

**Comment by IIIhorusIII** [comment]
@Neamar  ? we need that please

**Comment by Neamar** [comment]
Hi!

I discussed that directly with @psykzz but forgot to follow up here ;)

Runes & masteries are going away next patch (or in two patches?), so they won't be in Teamward. The replacement systems will be!

**Comment by IIIhorusIII** [comment]
hello,
i apologise for that odd request , i really forgot about upcoming patches
indeed .
for the feedback, i'd say you're such a huge help for us ! thank you .
waiting for more updates on the app

Le 14 oct. 2017 18:37, "Matthieu Bacconnier" <notifications@github.com> a
écrit :
