### ISSUE TITLE
F-Droid inclusion

### ISSUE THREAD

**Issue by Poussinou** [Neamar/teamward-client#37]
Hi,

Since this app is MIT licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind.

You can find some documentation [here](https://f-droid.org/docs/).

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by Neamar** [comment]
Hello!

https://github.com/Neamar/KISS is already on f-droid, and I don't have anything against it!

Would you be able to help with the process? I'm happy to merge anything you need.

**Comment by Poussinou** [comment]
I just saw that you're using proprietary libraries.

As you know, it won't be possible it include the app as it is in F-Droid. Would it be possible to have a different build flavor without google stuff?

**Comment by Neamar** [comment]
Hello!

I think push notifications are an important part of the app, and removing them probably makes the app useless -- there are other, better apps, and I'd say the main feature is the notification. So I'm unlikely to create a new build flavor :(

Sorry :( However, there isn't much development on the app anymore, so if you want to fork and create the custom build in the spirit of open source, you are very welcome :)

Thanks!

**Comment by Poussinou** [comment]
I understand your point ;) Could you then [add a signed apk](https://help.github.com/en/articles/creating-releases) with the last release here on Github, so that people without playstore can get the apk and the updates in the future?

**Comment by Neamar** [comment]
I've added a link: https://github.com/Neamar/teamward-client/releases/tag/v2.21.5 :)

Hopefully it works, since I've been using `aab` mostly for the past year.

**Comment by Poussinou** [comment]
Thanks :)
